version: '3.2'
services:
  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
    ulimits:
     memlock:
      soft: -1
      hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./bin/es:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-file: "7"
        max-size: "10m"
  indexer:
    container_name: indexer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-file: "7"
        max-size: "10m"